export const INDEX_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const DISCUSSION_ROUTE = '/discussions'
export const FRIENDS_ROUTE = '/friends'